name = "HybridSymbolics"
uuid = "d6b20ea1-67ec-4072-abcc-80972ac4980d"
authors = ["qfl3x <qfl3x@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Symbolics = "6.22.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
